export function TermsView() {
  return (
    <div className="legal-view">
      <h2>Terms of Use</h2>
      <p className="muted legal-updated">Last updated: 27 July 2026</p>

      <p>
        CCS SQL Academy is provided free of charge, as-is, for learning purposes. By using
        it, you agree to the following.
      </p>

      <h3>No warranty</h3>
      <p>
        The lessons, pass conditions, and execution-plan/statistics readings are provided
        without any warranty of accuracy, completeness, or fitness for a particular purpose.
        While the content is reviewed for technical correctness, mistakes can slip through —
        if you spot one, we'd appreciate a report via the{" "}
        <a href="https://github.com/johanccs/ccs-sql-academy" target="_blank" rel="noopener">
          GitHub repository
        </a>.
      </p>

      <h3>The AI tutor can be wrong</h3>
      <p>
        Answers from the "Sarge" tutor chat are generated by a third-party AI model and may be
        incomplete, outdated, or simply incorrect. Treat them as a study aid, not an
        authoritative source — verify anything important against the lesson text, the actual
        execution plan, or official SQL Server documentation before relying on it.
      </p>

      <h3>Acceptable use</h3>
      <p>
        Don't use the tutor chat to generate content unrelated to learning SQL Server
        performance tuning, and don't attempt to abuse, overload, or circumvent whatever rate
        limits protect the shared AI service. We may adjust or withdraw the tutor at any time
        without notice.
      </p>

      <h3>No liability</h3>
      <p>
        This is a personal, non-commercial project. To the fullest extent permitted by law, we
        are not liable for any loss or damage arising from your use of this site or reliance on
        its content.
      </p>

      <h3>Changes</h3>
      <p>
        These terms may change as the app evolves. Continued use after a change means you
        accept the updated terms.
      </p>

      <h3>Contact</h3>
      <p>
        Questions about these terms: <a href="mailto:johan.ccs@gmail.com">johan.ccs@gmail.com</a>.
      </p>
    </div>
  );
}
